export default `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BidaReels Catalog Admin</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0f1117;color:#edf0f7}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:30px 20px}header{display:flex;gap:16px;align-items:center;justify-content:space-between;margin-bottom:28px}h1{font-size:26px;margin:0}h2{font-size:20px}p{color:#b5bdce;line-height:1.6}button,input{font:inherit;font-size:15px;padding:11px 14px;border-radius:10px;border:1px solid #353c4a}button{background:#252c3b;color:#fff;cursor:pointer}button.primary{background:#ff9e23;color:#17110a;border-color:#ff9e23;font-weight:700}button:disabled{opacity:.5;cursor:wait}input{background:#141923;color:#fff;width:100%;margin-bottom:14px}label{display:block;margin:10px 0;font-size:15px}.panel{background:#191e29;border:1px solid #2a3242;border-radius:16px;padding:22px}.login{max-width:420px;margin:8vh auto}.actions{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:20px 0}.metric{padding:18px;border-radius:14px;background:#191e29;border:1px solid #2a3242}.metric b{display:block;font-size:28px}.metric span{color:#b5bdce;font-size:14px}.providers{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.card{padding:20px}.card h2{margin:0 0 10px}.status{font-size:14px;color:#ffb94f}.muted{font-size:14px;color:#aeb8c9}.error{color:#ff9e9e;overflow-wrap:anywhere}.toast{min-height:25px;padding:10px 0;color:#ffb94f}.preview{margin-top:18px;display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:12px}.poster{width:100%;aspect-ratio:2/3;object-fit:cover;border-radius:10px;background:#252c3b}.title{font-size:14px;overflow-wrap:anywhere}.hidden{display:none!important}@media(max-width:550px){main{padding:20px 14px}.summary{gap:8px}.metric{padding:12px}.metric b{font-size:23px}header{align-items:flex-start}h1{font-size:22px}}
</style></head><body><main><header><h1><span style="color:#ff9e23">BidaReels</span> · Catalog Admin</h1><button id="logout" class="hidden">Sign out</button></header><section id="login" class="panel login"><h2>Admin sign in</h2><form id="loginForm"><label for="email">Email</label><input id="email" type="email" autocomplete="username" required><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required><button class="primary">Sign in</button></form><p>Use the Firebase account enabled for catalog administration.</p></section><section id="workspace" class="hidden"><div class="actions"><button id="checkAll" class="primary">Check all providers</button><button id="syncAll">Sync all catalogs</button><button id="auto">Enable automatic checks</button><button id="refresh">Refresh status</button></div><div class="summary"><div class="metric"><b id="count">0</b><span>Published titles</span></div><div class="metric"><b id="ready">0</b><span>Published providers</span></div><div class="metric"><b id="queued">0</b><span>Waiting to sync</span></div></div><p id="job"></p><div id="providers" class="providers"></div><section class="panel hidden" id="previewPanel"><div class="actions"><h2 id="previewTitle">Catalog</h2><button id="closePreview">Close preview</button></div><div id="preview" class="preview"></div></section></section><div id="message" class="toast" role="status" aria-live="polite"></div></main><script>
let state=null, timer=null;
const el=id=>document.getElementById(id);const message=text=>el('message').textContent=text;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok){if(r.status===401)showLogin();throw new Error(d.error||'Request failed');}return d;}
function showLogin(){el('login').classList.remove('hidden');el('workspace').classList.add('hidden');el('logout').classList.add('hidden');clearTimeout(timer);}
function showWorkspace(){el('login').classList.add('hidden');el('workspace').classList.remove('hidden');el('logout').classList.remove('hidden');}
function textNode(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function date(ms){return ms?new Date(ms).toLocaleString():'Not yet';}
async function status(){clearTimeout(timer);try{state=await api('/admin/status');showWorkspace();el('count').textContent=state.providers.reduce((n,p)=>n+(p.count||0),0);el('ready').textContent=state.providers.filter(p=>p.version).length;el('queued').textContent=state.queue.length;el('auto').textContent=state.automation?'Disable automatic checks':'Enable automatic checks';el('job').textContent=state.job?'Working on '+state.job.key+' · page '+state.job.page:'No active sync';const grid=el('providers');grid.replaceChildren();for(const p of state.providers){const card=textNode('article','', 'panel card');card.append(textNode('h2',p.label),textNode('div',p.state||'Not synced','status'),textNode('p',(p.count||0)+' titles · Last published: '+date(p.updatedAt),'muted'),textNode('p','Last checked: '+date(p.checkedAt),'muted'));if(p.error)card.append(textNode('p',p.error,'error'));const actions=textNode('div','','actions');for(const [label,mode] of [['Check updates','check'],['Full sync','full'],['View titles','view'],['Export JSON','export']]){const b=textNode('button',label);b.onclick=()=>mode==='view'?preview(p):mode==='export'?exportJSON(p):sync(p.key,mode);actions.append(b);}card.append(actions);grid.append(card);}timer=setTimeout(status,5000);}catch(e){message(e.message);}}
async function sync(provider,mode){try{const r=await api('/admin/sync',{provider,mode});message(r.queued?'Sync queued. You may close this page.':'Already queued or running.');await status();}catch(e){message(e.message);}}
async function exportJSON(p){try{const d=await api('/admin/items?provider='+encodeURIComponent(p.key));const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=p.key+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){message(e.message);}}
async function preview(p){try{const d=await api('/admin/items?provider='+encodeURIComponent(p.key));el('previewTitle').textContent=p.label+' · '+d.items.length+' titles';const grid=el('preview');grid.replaceChildren();for(const i of d.items.slice(0,120)){const card=textNode('div','');const img=document.createElement('img');img.className='poster';img.src=i.posterUrl;img.alt=i.title;img.loading='lazy';img.referrerPolicy='no-referrer';card.append(img,textNode('p',i.title,'title'));grid.append(card);}el('previewPanel').classList.remove('hidden');el('previewPanel').scrollIntoView({behavior:'smooth'});}catch(e){message(e.message);}}
el('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/admin/login',{email:el('email').value,password:el('password').value});el('password').value='';message('Signed in.');await status();}catch(err){message(err.message);}finally{button.disabled=false;}};
el('logout').onclick=async()=>{try{await api('/admin/logout',{});showLogin();message('Signed out.');}catch(e){message(e.message);}};
el('checkAll').onclick=()=>sync('all','check');el('syncAll').onclick=()=>sync('all','full');el('refresh').onclick=status;el('closePreview').onclick=()=>el('previewPanel').classList.add('hidden');el('auto').onclick=async()=>{try{await api('/admin/automation',{enabled:!state.automation});await status();message(state.automation?'Automatic checks enabled.':'Automatic checks disabled.');}catch(e){message(e.message);}};status();
</script></body></html>`;
